version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
    links:
        - project1
        - project2
        - project3

  project1:
    build: ./
    expose:
        - "8080"

  project2:
    build: ./
    expose:
        - "8080"

  project3:
    build: ./
    expose:
        - "8080"

  mysql:
    image: mysql:latest
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=maoyan
